name: Build APK

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release_build:
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v3

       - name: set up JDK 17
         uses: actions/setup-java@v3
         with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

       - name: Setup Android SDK
         uses: android-actions/setup-android@v2

       - uses: gradle/gradle-build-action@v2
       - name: Build release APK
         run: gradle assembleRelease

       - name: Get Version Name
         id: get_version_name
         run: echo "::set-output name=version_name::$(grep 'versionName' app/build.gradle | sed -E 's/.*"(.+)"$/\1/')"

       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
           name: Release APK
           path: ${{ github.event.inputs.artifactName }}

       - name: Download artifact
         uses: actions/download-artifact@v3
         with:
           name: Release APK
           path: artifacts/release-apk
      
      
       - name: Publish GitHub release
         uses: softprops/action-gh-release@v1
         with:
           tag_name: ${{ github.event.inputs.tagName }}
           prerelease: ${{ github.events.inputs.prerelease }}
           draft: true
           body_path: ${{ github.workspace }}/GITHUB_CHANGELOG.md
           files: artifacts/release-apk/${{ github.event.inputs.artifactName }}
           name: ${{ steps.get_version_name.outputs.version_name }}       

