name: Build APK

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release_build:
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v3

       - name: set up JDK 17
         uses: actions/setup-java@v3
         with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

       - name: Setup Android SDK
         uses: android-actions/setup-android@v2

       - uses: gradle/gradle-build-action@v2
       - run: gradle assembleRelease

       - name: Get Version Name
         id: get_version_name
         run: echo "::set-output name=version_name::$(grep 'versionName' app/build.gradle | sed -E 's/.*"(.+)"$/\1/')"
       - name: Releasing using Hub
         uses: kyze8439690/action-release-releaseapk@master
         env:
           GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
           APP_FOLDER: app
       
    
