name: Release update
on:
  workflow_dispatch:
    inputs:
      artifactName:
        description: Artifact name
        type: string
        required: true
      tagName:
        description: Tag name
        type: string
        required: true
      prerelease:
        description: Prerelease
        type: boolean
        required: true
      releaseName:
        description: Release name
        type: string
        required: true
jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - name: Extract version info
        id: extract-versions
        run: |
          VERSION_NAME=$(grep "versionName" app/build.gradle | awk '{print $2}' | sed "s/'//g")
          VERSION_CODE=$(grep "versionCode" app/build.gradle | awk '{print $2}')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepRelease
      - name: Rename artifact
        run: mv "build/outputs/apk/lawnWithQuickstep/release/app-release.apk" "${{ github.event.inputs.artifactName }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release APK
          path: ${{ github.event.inputs.artifactName }}
  publish-github-release:
    runs-on: ubuntu-latest
    needs: build-release-apk
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Release APK
          path: artifacts/release-apk
      - name: Set up environment variables
        run: |
          VERSION_NAME=${{ env.VERSION_NAME }}
          VERSION_CODE=${{ env.VERSION_CODE }}
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tagName }}
          prerelease: ${{ github.events.inputs.prerelease }}
          draft: true
          body_path: ${{ github.workspace }}/GITHUB_CHANGELOG.md
          files: artifacts/release-apk/${{ github.event.inputs.artifactName }}
          name: "${{ github.event.inputs.releaseName }} ($VERSION_NAME-$VERSION_CODE)"
